name: First WorkFlow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-24.04
    steps:
      - name: Printing Greet
        run: echo "Hello world!!"
      - name: Print goodbye
        run: echo "Good Bye"
